<?php

namespace Database\Seeders;

use App\Models\Gateway;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GateWaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $GateWays = [
            [
                'id' => 1,
                'form_id' => 0,
                'code' => 101,
                'name' => 'Paypal',
                'alias' => 'Paypal',
                'image' => '663a38d7b455d1715091671.png',
                'status' => 0,
                'gateway_parameters' => '{"paypal_email":{"title":"PayPal Email","global":true,"value":"sb-owud61543012@business.example.com"}}',
                'supported_currencies' => [
                    'AUD' => 'AUD',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CZK' => 'CZK',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'HKD' => 'HKD',
                    'HUF' => 'HUF',
                    'INR' => 'INR',
                    'ILS' => 'ILS',
                    'JPY' => 'JPY',
                    'MYR' => 'MYR',
                    'MXN' => 'MXN',
                    'TWD' => 'TWD',
                    'NZD' => 'NZD',
                    'NOK' => 'NOK',
                    'PHP' => 'PHP',
                    'PLN' => 'PLN',
                    'GBP' => 'GBP',
                    'RUB' => 'RUB',
                    'SGD' => 'SGD',
                    'SEK' => 'SEK',
                    'CHF' => 'CHF',
                    'THB' => 'THB',
                    'USD' => '$'
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 2,
                'form_id' => 0,
                'code' => 102,
                'name' => 'Perfect Money',
                'alias' => 'PerfectMoney',
                'image' => '663a3920e30a31715091744.png',
                'status' => 0,
                'gateway_parameters' => '{"passphrase":{"title":"ALTERNATE PASSPHRASE","global":true,"value":"hR26aw02Q1eEeUPSIfuwNypXX"},"wallet_id":{"title":"PM Wallet","global":false,"value":""}}',
                'supported_currencies' => [
                    'USD' => '$',
                    'EUR' => '€'
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 3,
                'form_id' => 0,
                'code' => 103,
                'name' => 'Stripe Hosted',
                'alias' => 'Stripe',
                'image' => '663a39861cb9d1715091846.png',
                'status' => 0,
                'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"sk_test_51I6GGiCGv1sRiQlEi5v1or9eR0HVbuzdMd2rW4n3DxC8UKfz66R4X6n4yYkzvI2LeAIuRU9H99ZpY7XCNFC9xMs500vBjZGkKG"},"publishable_key":{"title":"PUBLISHABLE KEY","global":true,"value":"pk_test_51I6GGiCGv1sRiQlEOisPKrjBqQqqcFsw8mXNaZ2H2baN6R01NulFS7dKFji1NRRxuchoUTEDdB7ujKcyKYSVc0z500eth7otOM"}}',
                'supported_currencies' => [
                    'USD' => 'USD',
                    'AUD' => 'AUD',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'INR' => 'INR',
                    'JPY' => 'JPY',
                    'MXN' => 'MXN',
                    'MYR' => 'MYR',
                    'NOK' => 'NOK',
                    'NZD' => 'NZD',
                    'PLN' => 'PLN',
                    'SEK' => 'SEK',
                    'SGD' => 'SGD'
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 4,
                'form_id' => 0,
                'code' => 104,
                'name' => 'Skrill',
                'alias' => 'Skrill',
                'image' => '663a39494c4a91715091785.png',
                'status' => 0,
                'gateway_parameters' => '{"pay_to_email":{"title":"Skrill Email","global":true,"value":"merchant@skrill.com"},"secret_key":{"title":"Secret Key","global":true,"value":"---"}}',
                'supported_currencies' => [
                    'AED' => 'AED',
                    'AUD' => 'AUD',
                    'BGN' => 'BGN',
                    'BHD' => 'BHD',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'CZK' => 'CZK',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'HRK' => 'HRK',
                    'HUF' => 'HUF',
                    'ILS' => 'ILS',
                    'INR' => 'INR',
                    'ISK' => 'ISK',
                    'JOD' => 'JOD',
                    'JPY' => 'JPY',
                    'KRW' => 'KRW',
                    'KWD' => 'KWD',
                    'MAD' => 'MAD',
                    'MYR' => 'MYR',
                    'NOK' => 'NOK',
                    'NZD' => 'NZD',
                    'OMR' => 'OMR',
                    'PLN' => 'PLN',
                    'QAR' => 'QAR',
                    'RON' => 'RON',
                    'RSD' => 'RSD',
                    'SAR' => 'SAR',
                    'SEK' => 'SEK',
                    'SGD' => 'SGD',
                    'THB' => 'THB',
                    'TND' => 'TND',
                    'TRY' => 'TRY',
                    'TWD' => 'TWD',
                    'USD' => 'USD',
                    'ZAR' => 'ZAR',
                    'COP' => 'COP'
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 5,
                'form_id' => 0,
                'code' => 105,
                'name' => 'PayTM',
                'alias' => 'Paytm',
                'image' => '663a390f601191715091727.png',
                'status' => 0,
                'gateway_parameters' => '{"MID":{"title":"Merchant ID","global":true,"value":"DIY12386817555501617"},"merchant_key":{"title":"Merchant Key","global":true,"value":"bKMfNxPPf_QdZppa"},"WEBSITE":{"title":"Paytm Website","global":true,"value":"DIYtestingweb"},"INDUSTRY_TYPE_ID":{"title":"Industry Type","global":true,"value":"Retail"},"CHANNEL_ID":{"title":"CHANNEL ID","global":true,"value":"WEB"},"transaction_url":{"title":"Transaction URL","global":true,"value":"https:\\/\\/pguat.paytm.com\\/oltp-web\\/processTransaction"},"transaction_status_url":{"title":"Transaction STATUS URL","global":true,"value":"https:\\/\\/pguat.paytm.com\\/paytmchecksum\\/paytmCallback.jsp"}}',
                'supported_currencies' => [
                    'AUD' => 'AUD',
                    'ARS' => 'ARS',
                    'BDT' => 'BDT',
                    'BRL' => 'BRL',
                    'BGN' => 'BGN',
                    'CAD' => 'CAD',
                    'CLP' => 'CLP',
                    'CNY' => 'CNY',
                    'COP' => 'COP',
                    'HRK' => 'HRK',
                    'CZK' => 'CZK',
                    'DKK' => 'DKK',
                    'EGP' => 'EGP',
                    'EUR' => 'EUR',
                    'GEL' => 'GEL',
                    'GHS' => 'GHS',
                    'HKD' => 'HKD',
                    'HUF' => 'HUF',
                    'INR' => 'INR',
                    'IDR' => 'IDR',
                    'ILS' => 'ILS',
                    'JPY' => 'JPY',
                    'KES' => 'KES',
                    'MYR' => 'MYR',
                    'MXN' => 'MXN',
                    'MAD' => 'MAD',
                    'NPR' => 'NPR',
                    'NZD' => 'NZD',
                    'NGN' => 'NGN',
                    'NOK' => 'NOK',
                    'PKR' => 'PKR',
                    'PEN' => 'PEN',
                    'PHP' => 'PHP',
                    'PLN' => 'PLN',
                    'RON' => 'RON',
                    'RUB' => 'RUB',
                    'SGD' => 'SGD',
                    'ZAR' => 'ZAR',
                    'KRW' => 'KRW',
                    'LKR' => 'LKR',
                    'SEK' => 'SEK',
                    'CHF' => 'CHF',
                    'THB' => 'THB',
                    'TRY' => 'TRY',
                    'UGX' => 'UGX',
                    'UAH' => 'UAH',
                    'AED' => 'AED',
                    'GBP' => 'GBP',
                    'USD' => 'USD',
                    'VND' => 'VND',
                    'XOF' => 'XOF'
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 6,
                'form_id' => 0,
                'code' => 106,
                'name' => 'Payeer',
                'alias' => 'Payeer',
                'image' => '663a38c9e2e931715091657.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'merchant_id' => ['title' => 'Merchant ID', 'global' => true, 'value' => '866989763'],
                    'secret_key' => ['title' => 'Secret key', 'global' => true, 'value' => '7575']
                ]),
                'supported_currencies' => ['USD' => 'USD', 'EUR' => 'EUR', 'RUB' => 'RUB'],
                'crypto' => 0,
                'extra' => ['status' => ['title' => 'Status URL', 'value' => 'ipn.Payeer']],
                'description' => null,
            ],
            [
                'id' => 7,
                'form_id' => 0,
                'code' => 107,
                'name' => 'PayStack',
                'alias' => 'Paystack',
                'image' => '663a38fc814e91715091708.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'public_key' => ['title' => 'Public key', 'global' => true, 'value' => 'pk_test_cd330608eb47970889bca397ced55c1dd5ad3783'],
                    'secret_key' => ['title' => 'Secret key', 'global' => true, 'value' => 'sk_test_8a0b1f199362d7acc9c390bff72c4e81f74e2ac3']
                ]),
                'supported_currencies' => ['USD' => 'USD', 'NGN' => 'NGN'],
                'crypto' => 0,
                'extra' => [
                    'callback' => ['title' => 'Callback URL', 'value' => 'ipn.Paystack'],
                    'webhook' => ['title' => 'Webhook URL', 'value' => 'ipn.Paystack']
                ],
                'description' => null,
            ],
            [
                'id' => 8,
                'form_id' => 0,
                'code' => 109,
                'name' => 'Flutterwave',
                'alias' => 'Flutterwave',
                'image' => '663a36c2c34d61715091138.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'public_key' => ['title' => 'Public Key', 'global' => true, 'value' => '----------------'],
                    'secret_key' => ['title' => 'Secret Key', 'global' => true, 'value' => '-----------------------'],
                    'encryption_key' => ['title' => 'Encryption Key', 'global' => true, 'value' => '------------------']
                ]),
                'supported_currencies' => [
                    'BIF' => 'BIF',
                    'CAD' => 'CAD',
                    'CDF' => 'CDF',
                    'CVE' => 'CVE',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'GHS' => 'GHS',
                    'GMD' => 'GMD',
                    'GNF' => 'GNF',
                    'KES' => 'KES',
                    'LRD' => 'LRD',
                    'MWK' => 'MWK',
                    'MZN' => 'MZN',
                    'NGN' => 'NGN',
                    'RWF' => 'RWF',
                    'SLL' => 'SLL',
                    'STD' => 'STD',
                    'TZS' => 'TZS',
                    'UGX' => 'UGX',
                    'USD' => 'USD',
                    'XAF' => 'XAF',
                    'XOF' => 'XOF',
                    'ZMK' => 'ZMK',
                    'ZMW' => 'ZMW',
                    'ZWD' => 'ZWD'
                ],
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 9,
                'form_id' => 0,
                'code' => 110,
                'name' => 'RazorPay',
                'alias' => 'Razorpay',
                'image' => '663a393a527831715091770.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'key_id' => ['title' => 'Key Id', 'global' => true, 'value' => 'rzp_test_kiOtejPbRZU90E'],
                    'key_secret' => ['title' => 'Key Secret', 'global' => true, 'value' => 'osRDebzEqbsE1kbyQJ4y0re7']
                ]),
                'supported_currencies' => ['INR' => 'INR'],
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 10,
                'form_id' => 0,
                'code' => 111,
                'name' => 'Stripe Storefront',
                'alias' => 'StripeJs',
                'image' => '663a3995417171715091861.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'secret_key' => ['title' => 'Secret Key', 'global' => true, 'value' => 'sk_test_51I6GGiCGv1sRiQlEi5v1or9eR0HVbuzdMd2rW4n3DxC8UKfz66R4X6n4yYkzvI2LeAIuRU9H99ZpY7XCNFC9xMs500vBjZGkKG'],
                    'publishable_key' => ['title' => 'PUBLISHABLE KEY', 'global' => true, 'value' => 'pk_test_51I6GGiCGv1sRiQlEOisPKrjBqQqqcFsw8mXNaZ2H2baN6R01NulFS7dKFji1NRRxuchoUTEDdB7ujKcyKYSVc0z500eth7otOM']
                ]),
                'supported_currencies' => [
                    'USD' => 'USD',
                    'AUD' => 'AUD',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'INR' => 'INR',
                    'JPY' => 'JPY',
                    'MXN' => 'MXN',
                    'MYR' => 'MYR',
                    'NOK' => 'NOK',
                    'NZD' => 'NZD',
                    'PLN' => 'PLN',
                    'SEK' => 'SEK',
                    'SGD' => 'SGD'
                ],
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 11,
                'form_id' => 0,
                'code' => 112,
                'name' => 'Instamojo',
                'alias' => 'Instamojo',
                'image' => '663a384d54a111715091533.png',
                'status' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API KEY","global":true,"value":"test_2241633c3bc44a3de84a3b33969"},"auth_token":{"title":"Auth Token","global":true,"value":"test_279f083f7bebefd35217feef22d"},"salt":{"title":"Salt","global":true,"value":"19d38908eeff4f58b2ddda2c6d86ca25"}}',
                'supported_currencies' => ['INR' => 'INR'],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 12,
                'form_id' => 0,
                'code' => 501,
                'name' => 'Blockchain',
                'alias' => 'Blockchain',
                'image' => '663a35efd0c311715090927.png',
                'status' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"55529946-05ca-48ff-8710-f279d86b1cc5"},"xpub_code":{"title":"XPUB CODE","global":true,"value":"xpub6CKQ3xxWyBoFAF83izZCSFUorptEU9AF8TezhtWeMU5oefjX3sFSBw62Lr9iHXPkXmDQJJiHZeTRtD9Vzt8grAYRhvbz4nEvBu3QKELVzFK"}}',
                'supported_currencies' => ['BTC' => 'BTC'],
                'crypto' => 1,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 13,
                'form_id' => 0,
                'code' => 503,
                'name' => 'CoinPayments',
                'alias' => 'Coinpayments',
                'image' => '663a36a8d8e1d1715091112.png',
                'status' => 0,
                'gateway_parameters' => '{"public_key":{"title":"Public Key","global":true,"value":"---------------------"},"private_key":{"title":"Private Key","global":true,"value":"---------------------"},"merchant_id":{"title":"Merchant ID","global":true,"value":"---------------------"}}',
                'supported_currencies' => [
                    'BTC' => 'Bitcoin',
                    'BTC.LN' => 'Bitcoin (Lightning Network)',
                    'LTC' => 'Litecoin',
                    'CPS' => 'CPS Coin',
                    'VLX' => 'Velas',
                    'APL' => 'Apollo',
                    'AYA' => 'Aryacoin',
                    'BAD' => 'Badcoin',
                    'BCD' => 'Bitcoin Diamond',
                    'BCH' => 'Bitcoin Cash',
                    'BCN' => 'Bytecoin',
                    'BEAM' => 'BEAM',
                    'BITB' => 'Bean Cash',
                    'BLK' => 'BlackCoin',
                    'BSV' => 'Bitcoin SV',
                    'BTAD' => 'Bitcoin Adult',
                    'BTG' => 'Bitcoin Gold',
                    'BTT' => 'BitTorrent',
                    'CLOAK' => 'CloakCoin',
                    'CLUB' => 'ClubCoin',
                    'CRW' => 'Crown',
                    'CRYP' => 'CrypticCoin',
                    'CRYT' => 'CryTrExCoin',
                    'CURE' => 'CureCoin',
                    'DASH' => 'DASH',
                    'DCR' => 'Decred',
                    'DEV' => 'DeviantCoin',
                    'DGB' => 'DigiByte',
                    'DOGE' => 'Dogecoin',
                    'EBST' => 'eBoost',
                    'EOS' => 'EOS',
                    'ETC' => 'Ether Classic',
                    'ETH' => 'Ethereum',
                    'ETN' => 'Electroneum',
                    'EUNO' => 'EUNO',
                    'EXP' => 'EXP',
                    'Expanse' => 'Expanse',
                    'FLASH' => 'FLASH',
                    'GAME' => 'GameCredits',
                    'GLC' => 'Goldcoin',
                    'GRS' => 'Groestlcoin',
                    'KMD' => 'Komodo',
                    'LOKI' => 'LOKI',
                    'LSK' => 'LSK',
                    'MAID' => 'MaidSafeCoin',
                    'MUE' => 'MonetaryUnit',
                    'NAV' => 'NAV Coin',
                    'NEO' => 'NEO',
                    'NMC' => 'Namecoin',
                    'NVST' => 'NVO Token',
                    'NXT' => 'NXT',
                    'OMNI' => 'OMNI',
                    'PINK' => 'PinkCoin',
                    'PIVX' => 'PIVX',
                    'POT' => 'PotCoin',
                    'PPC' => 'Peercoin',
                    'PROC' => 'ProCurrency',
                    'PURA' => 'PURA',
                    'QTUM' => 'QTUM',
                    'RES' => 'Resistance',
                    'RVN' => 'Ravencoin',
                    'RVR' => 'RevolutionVR',
                    'SBD' => 'Steem Dollars',
                    'SMART' => 'SmartCash',
                    'SOXAX' => 'SOXAX',
                    'STEEM' => 'STEEM',
                    'STRAT' => 'STRAT',
                    'SYS' => 'Syscoin',
                    'TPAY' => 'TokenPay',
                    'TRIGGERS' => 'Triggers',
                    'TRX' => 'TRON',
                    'UBQ' => 'Ubiq',
                    'UNIT' => 'UniversalCurrency',
                    'USDT' => 'Tether USD (Omni Layer)',
                    'USDT.BEP20' => 'Tether USD (BSC Chain)',
                    'USDT.ERC20' => 'Tether USD (ERC20)',
                    'USDT.TRC20' => 'Tether USD (Tron/TRC20)',
                    'VTC' => 'Vertcoin',
                    'WAVES' => 'Waves',
                    'XCP' => 'Counterparty',
                    'XEM' => 'NEM',
                    'XMR' => 'Monero',
                    'XSN' => 'Stakenet',
                    'XSR' => 'SucreCoin',
                    'XVG' => 'VERGE',
                    'XZC' => 'ZCoin',
                    'ZEC' => 'ZCash',
                    'ZEN' => 'Horizen'
                ],
                'crypto' => 1,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 14,
                'form_id' => 0,
                'code' => 504,
                'name' => 'CoinPayments Fiat',
                'alias' => 'CoinpaymentsFiat',
                'image' => '663a36b7b841a1715091127.png',
                'status' => 0,
                'gateway_parameters' => '{"merchant_id":{"title":"Merchant ID","global":true,"value":"6515561"}}',
                'supported_currencies' => [
                    'USD' => 'USD',
                    'AUD' => 'AUD',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'CLP' => 'CLP',
                    'CNY' => 'CNY',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'INR' => 'INR',
                    'ISK' => 'ISK',
                    'JPY' => 'JPY',
                    'KRW' => 'KRW',
                    'NZD' => 'NZD',
                    'PLN' => 'PLN',
                    'RUB' => 'RUB',
                    'SEK' => 'SEK',
                    'SGD' => 'SGD',
                    'THB' => 'THB',
                    'TWD' => 'TWD'
                ],

                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 15,
                'form_id' => 0,
                'code' => 505,
                'name' => 'Coingate',
                'alias' => 'Coingate',
                'image' => '663a368e753381715091086.png',
                'status' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"6354mwVCEw5kHzRJ6thbGo-N"}}',
                'supported_currencies' => [
                    'USD' => 'USD',
                    'EUR' => 'EUR'
                ],

                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 16,
                'form_id' => 0,
                'code' => 506,
                'name' => 'Coinbase Commerce',
                'alias' => 'CoinbaseCommerce',
                'image' => '663a367e46ae51715091070.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'api_key' => [
                        'title' => 'API Key',
                        'global' => true,
                        'value' => 'c47cd7df-d8e8-424b-a20a'
                    ],
                    'secret' => [
                        'title' => 'Webhook Shared Secret',
                        'global' => true,
                        'value' => '55871878-2c32-4f64-ab66'
                    ]
                ]),
                'supported_currencies' => [
                    'USD' => 'USD',
                    'EUR' => 'EUR',
                    'JPY' => 'JPY',
                    'GBP' => 'GBP',
                    'AUD' => 'AUD',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'CNY' => 'CNY',
                    'SEK' => 'SEK',
                    'NZD' => 'NZD',
                    'MXN' => 'MXN',
                    'SGD' => 'SGD',
                    'HKD' => 'HKD',
                    'NOK' => 'NOK',
                    'KRW' => 'KRW',
                    'TRY' => 'TRY',
                    'RUB' => 'RUB',
                    'INR' => 'INR',
                    'BRL' => 'BRL',
                    'ZAR' => 'ZAR',
                    'AED' => 'AED',
                    'AFN' => 'AFN',
                    'ALL' => 'ALL',
                    'AMD' => 'AMD',
                    'ANG' => 'ANG',
                    'AOA' => 'AOA',
                    'ARS' => 'ARS',
                    'AWG' => 'AWG',
                    'AZN' => 'AZN',
                    'BAM' => 'BAM',
                    'BBD' => 'BBD',
                    'BDT' => 'BDT',
                    'BGN' => 'BGN',
                    'BHD' => 'BHD',
                    'BIF' => 'BIF',
                    'BMD' => 'BMD',
                    'BND' => 'BND',
                    'BOB' => 'BOB',
                    'BSD' => 'BSD',
                    'BTN' => 'BTN',
                    'BWP' => 'BWP',
                    'BYN' => 'BYN',
                    'BZD' => 'BZD',
                    'CDF' => 'CDF',
                    'CLF' => 'CLF',
                    'CLP' => 'CLP',
                    'COP' => 'COP',
                    'CRC' => 'CRC',
                    'CUC' => 'CUC',
                    'CUP' => 'CUP',
                    'CVE' => 'CVE',
                    'CZK' => 'CZK',
                    'DJF' => 'DJF',
                    'DKK' => 'DKK',
                    'DOP' => 'DOP',
                    'DZD' => 'DZD',
                    'EGP' => 'EGP',
                    'ERN' => 'ERN',
                    'ETB' => 'ETB',
                    'FJD' => 'FJD',
                    'FKP' => 'FKP',
                    'GEL' => 'GEL',
                    'GGP' => 'GGP',
                    'GHS' => 'GHS',
                    'GIP' => 'GIP',
                    'GMD' => 'GMD',
                    'GNF' => 'GNF',
                    'GTQ' => 'GTQ',
                    'GYD' => 'GYD',
                    'HNL' => 'HNL',
                    'HRK' => 'HRK',
                    'HTG' => 'HTG',
                    'HUF' => 'HUF',
                    'IDR' => 'IDR',
                    'ILS' => 'ILS',
                    'IMP' => 'IMP',
                    'IQD' => 'IQD',
                    'IRR' => 'IRR',
                    'ISK' => 'ISK',
                    'JEP' => 'JEP',
                    'JMD' => 'JMD',
                    'JOD' => 'JOD',
                    'KES' => 'KES',
                    'KGS' => 'KGS',
                    'KHR' => 'KHR',
                    'KMF' => 'KMF',
                    'KPW' => 'KPW',
                    'KWD' => 'KWD',
                    'KYD' => 'KYD',
                    'KZT' => 'KZT',
                    'LAK' => 'LAK',
                    'LBP' => 'LBP',
                    'LKR' => 'LKR',
                    'LRD' => 'LRD',
                    'LSL' => 'LSL',
                    'LYD' => 'LYD',
                    'MAD' => 'MAD',
                    'MDL' => 'MDL',
                    'MGA' => 'MGA',
                    'MKD' => 'MKD',
                    'MMK' => 'MMK',
                    'MNT' => 'MNT',
                    'MOP' => 'MOP',
                    'MRO' => 'MRO',
                    'MUR' => 'MUR',
                    'MVR' => 'MVR',
                    'MWK' => 'MWK',
                    'MYR' => 'MYR',
                    'MZN' => 'MZN',
                    'NAD' => 'NAD',
                    'NGN' => 'NGN',
                    'NIO' => 'NIO',
                    'NPR' => 'NPR',
                    'OMR' => 'OMR',
                    'PAB' => 'PAB',
                    'PEN' => 'PEN',
                    'PGK' => 'PGK',
                    'PHP' => 'PHP',
                    'PKR' => 'PKR',
                    'PLN' => 'PLN',
                    'PYG' => 'PYG',
                    'QAR' => 'QAR',
                    'RON' => 'RON',
                    'RSD' => 'RSD',
                    'RWF' => 'RWF',
                    'SAR' => 'SAR',
                    'SBD' => 'SBD',
                    'SCR' => 'SCR',
                    'SDG' => 'SDG',
                    'SHP' => 'SHP',
                    'SLL' => 'SLL',
                    'SOS' => 'SOS',
                    'SRD' => 'SRD',
                    'SSP' => 'SSP',
                    'STD' => 'STD',
                    'SVC' => 'SVC',
                    'SYP' => 'SYP',
                    'SZL' => 'SZL',
                    'THB' => 'THB',
                    'TJS' => 'TJS',
                    'TMT' => 'TMT',
                    'TND' => 'TND',
                    'TOP' => 'TOP',
                    'TTD' => 'TTD',
                    'TWD' => 'TWD',
                    'TZS' => 'TZS',
                    'UAH' => 'UAH',
                    'UGX' => 'UGX',
                    'UYU' => 'UYU',
                    'UZS' => 'UZS',
                    'VEF' => 'VEF',
                    'VND' => 'VND',
                    'VUV' => 'VUV',
                    'WST' => 'WST',
                    'XAF' => 'XAF',
                    'XAG' => 'XAG',
                    'XAU' => 'XAU',
                    'XCD' => 'XCD',
                    'XDR' => 'XDR',
                    'XOF' => 'XOF',
                    'XPD' => 'XPD',
                    'XPF' => 'XPF',
                    'XPT' => 'XPT',
                    'YER' => 'YER',
                    'ZMW' => 'ZMW',
                    'ZWL' => 'ZWL',
                ],
                'crypto' => 0,
                'extra' => [
                    'endpoint' => [
                        'title' => 'Webhook Endpoint',
                        'value' => 'ipn.CoinbaseCommerce'
                    ]
                ],
                'description' => NULL,
            ],
            [
                'id' => 17,
                'form_id' => 0,
                'code' => 113,
                'name' => 'Paypal Express',
                'alias' => 'PaypalSdk',
                'image' => '663a38ed101a61715091693.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'clientId' => [
                        'title' => 'Paypal Client ID',
                        'global' => true,
                        'value' => 'Ae0-tixtSV7DvLwIh3Bmu7JvHrjh5EfGdXr_cEklKAVjjezRZ747BxKILiBdzlKKyp-W8W_T7CKH1Ken'
                    ],
                    'clientSecret' => [
                        'title' => 'Client Secret',
                        'global' => true,
                        'value' => 'EOhbvHZgFNO21soQJT1L9Q00M3rK6PIEsdiTgXRBt2gtGtxwRer5JvKnVUGNU5oE63fFnjnYY7hq3HBA'
                    ]
                ]),
                'supported_currencies' => [
                    'AUD' => 'AUD',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CZK' => 'CZK',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'HKD' => 'HKD',
                    'HUF' => 'HUF',
                    'INR' => 'INR',
                    'ILS' => 'ILS',
                    'JPY' => 'JPY',
                    'MYR' => 'MYR',
                    'MXN' => 'MXN',
                    'TWD' => 'TWD',
                    'NZD' => 'NZD',
                    'NOK' => 'NOK',
                    'PHP' => 'PHP',
                    'PLN' => 'PLN',
                    'GBP' => 'GBP',
                    'RUB' => 'RUB',
                    'SGD' => 'SGD',
                    'SEK' => 'SEK',
                    'CHF' => 'CHF',
                    'THB' => 'THB',
                    'USD' => '$',
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 18,
                'form_id' => 0,
                'code' => 114,
                'name' => 'Stripe Checkout',
                'alias' => 'StripeV3',
                'image' => '663a39afb519f1715091887.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'secret_key' => [
                        'title' => 'Secret Key',
                        'global' => true,
                        'value' => 'sk_test_51I6GGiCGv1sRiQlEi5v1or9eR0HVbuzdMd2rW4n3DxC8UKfz66R4X6n4yYkzvI2LeAIuRU9H99ZpY7XCNFC9xMs500vBjZGkKG'
                    ],
                    'publishable_key' => [
                        'title' => 'PUBLISHABLE KEY',
                        'global' => true,
                        'value' => 'pk_test_51I6GGiCGv1sRiQlEOisPKrjBqQqqcFsw8mXNaZ2H2baN6R01NulFS7dKFji1NRRxuchoUTEDdB7ujKcyKYSVc0z500eth7otOM'
                    ],
                    'end_point' => [
                        'title' => 'End Point Secret',
                        'global' => true,
                        'value' => 'whsec_lUmit1gtxwKTveLnSe88xCSDdnPOt8g5'
                    ]
                ]),
                'supported_currencies' => [
                    'USD' => 'USD',
                    'AUD' => 'AUD',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'INR' => 'INR',
                    'JPY' => 'JPY',
                    'MXN' => 'MXN',
                    'MYR' => 'MYR',
                    'NOK' => 'NOK',
                    'NZD' => 'NZD',
                    'PLN' => 'PLN',
                    'SEK' => 'SEK',
                    'SGD' => 'SGD',
                ],
                'crypto' => 0,
                'extra' => [
                    'webhook' => [
                        'title' => 'Webhook Endpoint',
                        'value' => 'ipn.StripeV3'
                    ]
                ],
                'description' => NULL,
            ],
            [
                'id' => 19,
                'form_id' => 0,
                'code' => 115,
                'name' => 'Mollie',
                'alias' => 'Mollie',
                'image' => '663a387ec69371715091582.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'mollie_email' => [
                        'title' => 'Mollie Email',
                        'global' => true,
                        'value' => 'vi@gmail.com',
                    ],
                    'api_key' => [
                        'title' => 'API KEY',
                        'global' => true,
                        'value' => 'test_cucfwKTWfft9s337qsVfn5CC4vNkrn',
                    ],
                ]),
                'supported_currencies' => json_encode([
                    'AED' => 'AED',
                    'AUD' => 'AUD',
                    'BGN' => 'BGN',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'CZK' => 'CZK',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'HRK' => 'HRK',
                    'HUF' => 'HUF',
                    'ILS' => 'ILS',
                    'ISK' => 'ISK',
                    'JPY' => 'JPY',
                    'MXN' => 'MXN',
                    'MYR' => 'MYR',
                    'NOK' => 'NOK',
                    'NZD' => 'NZD',
                    'PHP' => 'PHP',
                    'PLN' => 'PLN',
                    'RON' => 'RON',
                    'RUB' => 'RUB',
                    'SEK' => 'SEK',
                    'SGD' => 'SGD',
                    'THB' => 'THB',
                    'TWD' => 'TWD',
                    'USD' => 'USD',
                    'ZAR' => 'ZAR',
                ]),
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 20,
                'form_id' => 0,
                'code' => 116,
                'name' => 'Cashmaal',
                'alias' => 'Cashmaal',
                'image' => '663a361b16bd11715090971.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'web_id' => [
                        'title' => 'Web Id',
                        'global' => true,
                        'value' => '3748',
                    ],
                    'ipn_key' => [
                        'title' => 'IPN Key',
                        'global' => true,
                        'value' => '546254628759524554647987',
                    ],
                ]),
                'supported_currencies' => [
                    'PKR' => 'PKR',
                    'USD' => 'USD',
                ],
                'crypto' => 0,
                'extra' => [
                    'webhook' => [
                        'title' => 'IPN URL',
                        'value' => 'ipn.Cashmaal',
                    ],
                ],
                'description' => null,
            ],
            [
                'id' => 21,
                'form_id' => 0,
                'code' => 119,
                'name' => 'Mercado Pago',
                'alias' => 'MercadoPago',
                'image' => '663a386c714a91715091564.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'access_token' => [
                        'title' => 'Access Token',
                        'global' => true,
                        'value' => 'APP_USR-7924565816849832-082312-21941521997fab717db925cf1ea2c190-1071840315',
                    ],
                ]),
                'supported_currencies' => [
                    'USD' => 'USD',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'NOK' => 'NOK',
                    'PLN' => 'PLN',
                    'SEK' => 'SEK',
                    'AUD' => 'AUD',
                    'NZD' => 'NZD',
                ],
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 22,
                'form_id' => 0,
                'code' => 120,
                'name' => 'Authorize.net',
                'alias' => 'Authorize',
                'image' => '663a35b9ca5991715090873.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'login_id' => [
                        'title' => 'Login ID',
                        'global' => true,
                        'value' => '59e4P9DBcZv',
                    ],
                    'transaction_key' => [
                        'title' => 'Transaction Key',
                        'global' => true,
                        'value' => '47x47TJyLw2E7DbR',
                    ],
                ]),
                'supported_currencies' => [
                    'USD' => 'USD',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'NOK' => 'NOK',
                    'PLN' => 'PLN',
                    'SEK' => 'SEK',
                    'AUD' => 'AUD',
                    'NZD' => 'NZD',
                ],
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 23,
                'form_id' => 0,
                'code' => 121,
                'name' => 'NMI',
                'alias' => 'NMI',
                'image' => '663a3897754cf1715091607.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'api_key' => [
                        'title' => 'API Key',
                        'global' => true,
                        'value' => '2F822Rw39fx762MaV7Yy86jXGTC7sCDy',
                    ],
                ]),
                'supported_currencies' => [
                    'AED' => 'AED',
                    'ARS' => 'ARS',
                    'AUD' => 'AUD',
                    'BOB' => 'BOB',
                    'BRL' => 'BRL',
                    'CAD' => 'CAD',
                    'CHF' => 'CHF',
                    'CLP' => 'CLP',
                    'CNY' => 'CNY',
                    'COP' => 'COP',
                    'DKK' => 'DKK',
                    'EUR' => 'EUR',
                    'GBP' => 'GBP',
                    'HKD' => 'HKD',
                    'IDR' => 'IDR',
                    'ILS' => 'ILS',
                    'INR' => 'INR',
                    'JPY' => 'JPY',
                    'KRW' => 'KRW',
                    'MXN' => 'MXN',
                    'MYR' => 'MYR',
                    'NOK' => 'NOK',
                    'NZD' => 'NZD',
                    'PEN' => 'PEN',
                    'PHP' => 'PHP',
                    'PLN' => 'PLN',
                    'PYG' => 'PYG',
                    'RUB' => 'RUB',
                    'SEC' => 'SEC',
                    'SGD' => 'SGD',
                    'THB' => 'THB',
                    'TRY' => 'TRY',
                    'TWD' => 'TWD',
                    'USD' => 'USD',
                    'ZAR' => 'ZAR',
                ],
                'crypto' => 0,
                'extra' => null,
                'description' => null,
            ],
            [
                'id' => 24,
                'form_id' => 0,
                'code' => 507,
                'name' => 'BTCPay',
                'alias' => 'BTCPay',
                'image' => '663a35cd25a8d1715090893.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'store_id' => [
                        'title' => 'Store Id',
                        'global' => true,
                        'value' => 'HsqFVTXSeUFJu7caoYZc3CTnP8g5LErVdHhEXPVTheHf',
                    ],
                    'api_key' => [
                        'title' => 'Api Key',
                        'global' => true,
                        'value' => '4436bd706f99efae69305e7c4eff4780de1335ce',
                    ],
                    'server_name' => [
                        'title' => 'Server Name',
                        'global' => true,
                        'value' => 'https://testnet.demo.btcpayserver.org',
                    ],
                    'secret_code' => [
                        'title' => 'Secret Code',
                        'global' => true,
                        'value' => 'SUCdqPn9CDkY7RmJHfpQVHP2Lf2',
                    ],
                ]),
                'supported_currencies' => [
                    'BTC' => 'Bitcoin',
                    'LTC' => 'Litecoin',
                ],
                'crypto' => 1,
                'extra' => [
                    'webhook' => [
                        'title' => 'IPN URL',
                        'value' => 'ipn.BTCPay',
                    ],
                ],
                'description' => null,
            ],
            [
                'id' => 25,
                'form_id' => 0,
                'code' => 508,
                'name' => 'Now payments hosted',
                'alias' => 'NowPaymentsHosted',
                'image' => '663a38b8d57a81715091640.png',
                'status' => 0,
                'gateway_parameters' => json_encode([
                    'api_key' => [
                        'title' => 'API Key',
                        'global' => true,
                        'value' => '--------',
                    ],
                    'secret_key' => [
                        'title' => 'Secret Key',
                        'global' => true,
                        'value' => '------------',
                    ],
                ]),
                'supported_currencies' => [
                    'BTG' => 'BTG',
                    'ETH' => 'ETH',
                    'XMR' => 'XMR',
                    'ZEC' => 'ZEC',
                    'XVG' => 'XVG',
                    'ADA' => 'ADA',
                    'LTC' => 'LTC',
                    'BCH' => 'BCH',
                    'QTUM' => 'QTUM',
                    'DASH' => 'DASH',
                    'XLM' => 'XLM',
                    'XRP' => 'XRP',
                    'XEM' => 'XEM',
                    'DGB' => 'DGB',
                    'LSK' => 'LSK',
                    'DOGE' => 'DOGE',
                    'TRX' => 'TRX',
                    'KMD' => 'KMD',
                    'REP' => 'REP',
                    'BAT' => 'BAT',
                    'ARK' => 'ARK',
                    'WAVES' => 'WAVES',
                    'BNB' => 'BNB',
                    'XZC' => 'XZC',
                    'NANO' => 'NANO',
                    'TUSD' => 'TUSD',
                    'VET' => 'VET',
                    'ZEN' => 'ZEN',
                    'GRS' => 'GRS',
                    'FUN' => 'FUN',
                    'NEO' => 'NEO',
                    'GAS' => 'GAS',
                    'PAX' => 'PAX',
                    'USDC' => 'USDC',
                    'ONT' => 'ONT',
                    'XTZ' => 'XTZ',
                    'LINK' => 'LINK',
                    'RVN' => 'RVN',
                    'BNBMAINNET' => 'BNBMAINNET',
                    'ZIL' => 'ZIL',
                    'BCD' => 'BCD',
                    'USDT' => 'USDT',
                    'USDTERC20' => 'USDTERC20',
                    'CRO' => 'CRO',
                    'DAI' => 'DAI',
                    'HT' => 'HT',
                    'WABI' => 'WABI',
                    'BUSD' => 'BUSD',
                    'ALGO' => 'ALGO',
                    'USDTTRC20' => 'USDTTRC20',
                    'GT' => 'GT',
                    'STPT' => 'STPT',
                    'AVA' => 'AVA',
                    'SXP' => 'SXP',
                    'UNI' => 'UNI',
                    'OKB' => 'OKB',
                    'BTC' => 'BTC',
                ],
                'crypto' => 1,
                'extra' => '',
                'description' => null,
            ],
            [
                'id' => 26,
                'form_id' => 0,
                'code' => 509,
                'name' => 'Now payments checkout',
                'alias' => 'NowPaymentsCheckout',
                'image' => '663a38a59d2541715091621.png',
                'status' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"---------------"},"secret_key":{"title":"Secret Key","global":true,"value":"-----------"}}',
                'supported_currencies' => [
                    'USD' => 'USD',
                    'EUR' => 'EUR',
                ],
                'crypto' => 1,
                'extra' => '',
                'description' => NULL,
            ],
            [
                'id' => 27,
                'form_id' => 0,
                'code' => 122,
                'name' => '2Checkout',
                'alias' => 'TwoCheckout',
                'image' => '663a39b8e64b91715091896.png',
                'status' => 0,
                'gateway_parameters' => '{"merchant_code":{"title":"Merchant Code","global":true,"value":"253248016872"},"secret_key":{"title":"Secret Key","global":true,"value":"eQM)ID@&vG84u!O*g[p+"}}',
                'supported_currencies' => [
                    'AFN' => 'AFN',
                    'ALL' => 'ALL',
                    'DZD' => 'DZD',
                    'ARS' => 'ARS',
                    'AUD' => 'AUD',
                    'AZN' => 'AZN',
                    'BSD' => 'BSD',
                    'BDT' => 'BDT',
                    'BBD' => 'BBD',
                    'BZD' => 'BZD',
                    'BMD' => 'BMD',
                    'BOB' => 'BOB',
                    'BWP' => 'BWP',
                    'BRL' => 'BRL',
                    'GBP' => 'GBP',
                    'BND' => 'BND',
                    'BGN' => 'BGN',
                    'CAD' => 'CAD',
                    'CLP' => 'CLP',
                    'CNY' => 'CNY',
                    'COP' => 'COP',
                    'CRC' => 'CRC',
                    'HRK' => 'HRK',
                    'CZK' => 'CZK',
                    'DKK' => 'DKK',
                    'DOP' => 'DOP',
                    'XCD' => 'XCD',
                    'EGP' => 'EGP',
                    'EUR' => 'EUR',
                    'FJD' => 'FJD',
                    'GTQ' => 'GTQ',
                    'HKD' => 'HKD',
                    'HNL' => 'HNL',
                    'HUF' => 'HUF',
                    'INR' => 'INR',
                    'IDR' => 'IDR',
                    'ILS' => 'ILS',
                    'JMD' => 'JMD',
                    'JPY' => 'JPY',
                    'KZT' => 'KZT',
                    'KES' => 'KES',
                    'LAK' => 'LAK',
                    'MMK' => 'MMK',
                    'LBP' => 'LBP',
                    'LRD' => 'LRD',
                    'MOP' => 'MOP',
                    'MYR' => 'MYR',
                    'MVR' => 'MVR',
                    'MRO' => 'MRO',
                    'MUR' => 'MUR',
                    'MXN' => 'MXN',
                    'MAD' => 'MAD',
                    'NPR' => 'NPR',
                    'TWD' => 'TWD',
                    'NZD' => 'NZD',
                    'NIO' => 'NIO',
                    'NOK' => 'NOK',
                    'PKR' => 'PKR',
                    'PGK' => 'PGK',
                    'PEN' => 'PEN',
                    'PHP' => 'PHP',
                    'PLN' => 'PLN',
                    'QAR' => 'QAR',
                    'RON' => 'RON',
                    'RUB' => 'RUB',
                    'WST' => 'WST',
                    'SAR' => 'SAR',
                    'SCR' => 'SCR',
                    'SGD' => 'SGD',
                    'SBD' => 'SBD',
                    'ZAR' => 'ZAR',
                    'KRW' => 'KRW',
                    'LKR' => 'LKR',
                    'SEK' => 'SEK',
                    'CHF' => 'CHF',
                    'SYP' => 'SYP',
                    'THB' => 'THB',
                    'TOP' => 'TOP',
                    'TTD' => 'TTD',
                    'TRY' => 'TRY',
                    'UAH' => 'UAH',
                    'AED' => 'AED',
                    'USD' => 'USD',
                    'VUV' => 'VUV',
                    'VND' => 'VND',
                    'XOF' => 'XOF',
                    'YER' => 'YER',
                ],
                'crypto' => 0,
                'extra' => [
                    'approved_url' => [
                        'title' => 'Approved URL',
                        'value' => 'ipn.TwoCheckout',
                    ],
                ],
                'description' => NULL,
            ],
            [
                'id' => 28,
                'form_id' => 2,
                'code' => 1000,
                'name' => 'Bank Transfer',
                'alias' => 'bank_transfer',
                'image' => '678d13b9bc0ba1737298873.png',
                'status' => 1,
                'gateway_parameters' => '[]',
                'supported_currencies' => '[]',
                'crypto' => 0,
                'extra' => NULL,
                'description' => '<div style="border-left: 3px solid rgb(181, 176, 176); padding: 12px; margin: 30px 0px; background: rgb(249, 249, 249); border-radius: 3px;"><p style="font-style: italic; margin-bottom: 10px; font-weight: bold; font-size: 17px;">Send the amount to the below bank information</p><p style="font-style: italic; margin-bottom: 0px;"></p><p style="margin-bottom: 0px;"><b><font color="#000000">Bank Name: Sampath Bank</font></b></p><p style="margin-bottom: 0px;"><b><font color="#000000">Branch: Maharagama Super</font></b></p><p style="margin-bottom: 0px;"><b><font color="#000000">Name: Facecoin Lankan INC</font></b></p><p style="margin-bottom: 0px;"><b><font color="#000000">Account Number: 109214014164</font></b></p></div>',

            ],
            [
                'id' => 29,
                'form_id' => 0,
                'code' => 510,
                'name' => 'Binance',
                'alias' => 'Binance',
                'image' => '663a35db4fd621715090907.png',
                'status' => 0,
                'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"tsu3tjiq0oqfbtmlbevoeraxhfbp3brejnm9txhjxcp4to29ujvakvfl1ibsn3ja"},"secret_key":{"title":"Secret Key","global":true,"value":"jzngq4t04ltw8d4iqpi7admfl8tvnpehxnmi34id1zvfaenbwwvsvw7llw3zdko8"},"merchant_id":{"title":"Merchant ID","global":true,"value":"231129033"}}',
                'supported_currencies' => [
                    'BTC' => 'Bitcoin',
                    'USD' => 'USD',
                    'BNB' => 'BNB',
                ],
                'crypto' => 1,
                'extra' => [
                    'cron' => [
                        'title' => 'Cron Job URL',
                        'value' => 'ipn.Binance',
                    ],
                ],
                'description' => NULL,
            ],
            [
                'id' => 30,
                'form_id' => 0,
                'code' => 124,
                'name' => 'SslCommerz',
                'alias' => 'SslCommerz',
                'image' => '663a397a70c571715091834.png',
                'status' => 0,
                'gateway_parameters' => '{"store_id":{"title":"Store ID","global":true,"value":"---------"},"store_password":{"title":"Store Password","global":true,"value":"----------"}}',
                'supported_currencies' => [
                    'BDT' => 'BDT',
                    'USD' => 'USD',
                    'EUR' => 'EUR',
                    'SGD' => 'SGD',
                    'INR' => 'INR',
                    'MYR' => 'MYR',
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 31,
                'form_id' => 0,
                'code' => 125,
                'name' => 'Aamarpay',
                'alias' => 'Aamarpay',
                'image' => '663a34d5d1dfc1715090645.png',
                'status' => 0,
                'gateway_parameters' => '{"store_id":{"title":"Store ID","global":true,"value":"---------"},"signature_key":{"title":"Signature Key","global":true,"value":"----------"}}',
                'supported_currencies' => [
                    'BDT' => 'BDT',
                ],
                'crypto' => 0,
                'extra' => NULL,
                'description' => NULL,
            ],
            [
                'id' => 32,
                'form_id' => 3,
                'code' => 1001,
                'name' => 'Binance',
                'alias' => 'binance',
                'image' => '679f887d196771738508413.jpg',
                'status' => 1,
                'gateway_parameters' => '[]',
                'supported_currencies' => '[]',
                'crypto' => 0,
                'extra' => NULL,
                'description' => '<div style="text-align: center;"><b>Binance ID -&nbsp;</b><span style="background-color: var(--bs-card-bg); text-align: var(--bs-body-text-align);"><font color="#212529"><b>184197748</b></font></span></div>',
            ]
        ];

        foreach ($GateWays as $GateWay) {
            Gateway::create($GateWay);
        }
    }
}
